### ISSUE TITLE
Изменение роли пользователя

### ISSUE THREAD

**Issue by Anna-Prokhorova** [outsidious/fit-internship-backend#1]
- Нет возможности менять роли пользователя при запросе на обновление пользователя

![image](https://user-images.githubusercontent.com/59168625/194511126-e6e43076-ea16-4a7e-afce-66d12a2d61e7.png)

**Comment by Wilddangerousbee** [comment]
Запрос добавил. просьба протестировать и закрыть ишью
![image](https://user-images.githubusercontent.com/48296633/194627922-c0cda9c6-faea-4b51-be06-bf9ba8c7d17d.png)
